### ISSUE TITLE
npx hardhat test

### ISSUE THREAD

**Issue by Joe-mcgee** [OlympusDAO/olympus-contracts#107]
Hi, just trying to run your test suite to see how your contract works.  I usually start with trying to run ``npx hardhat test`` Some mocks appear missing that are easy to get, like the TestTokens 1&2 and the uniswap v2-core stuff, but I'm not sure where to find this one.  I see a `StandardBondingCalculator` but no `DebtCalculator` in the repo.

https://github.com/OlympusDAO/olympus-contracts/blob/5063980ff34e6838bb4fad5280a4bd12627c2e26/test/OlympusBondingCalculator-Unit.test.waffle.chai.ethers.js#L49

Am I missing some docs around local deployments?  I'm seeing some people ask around for it, and even a dockerized e-2-e in the PRs, but other than that I'm not sure.  I've also hopped around the Development Discord Server, but I'm not looking to commit time to the project, just to do a technical due dilligence

Thanks!

**Comment by Joe-mcgee** [comment]
Hmm found 
https://github.com/OlympusDAO/olympus-contracts/pull/36/files

Looks like this code will likely get depreciated, Perhaps I can avoid it and just run each test separate

**Comment by sam-goodwin** [comment]
Running into the same problem, code seems incomplete.

**Comment by Joe-mcgee** [comment]
@sam-goodwin Just looking at another issue looks like the main branch v1.1 isn't maintained, but Version-2 may be, perhaps we can try there

Could you try working with the V2 branch? V1.1 is not actively maintained.
It would be great if Olympus Team updates the default branch for this project too.

_Originally posted by @NoblePaladin in https://github.com/OlympusDAO/olympus-contracts/issues/110#issuecomment-980199651_

**Comment by NoblePaladin** [comment]
@Joe-mcgee, @sam-goodwin 

It seems the team at Olympus are a bit busy prototyping things.
Totally understandable.

Our (soon to be) hardfork at ETNA DAO will be highly driven by community feedback.
So I encourage you to keep up to date with our project over there.

https://github.com/etnadao

Thank you friends

**Comment by Joe-mcgee** [comment]
@NoblePaladin 
Neat, it'll be interesting for me to see how you guys take the code apart and make it yours

**Comment by ind-igo** [comment]
Our tests are rudimentary currently but we are slowly adding more as development continues on V2.
