### ISSUE TITLE
How to distribute in rebase mechanism

### ISSUE THREAD

**Issue by legendarydev007** [OlympusDAO/olympus-contracts#109]
Hello, everyone.
I have researched OHM contract and have learnt much more.
But I have some questions about rebase mechanism.
I have understood like this.
When user stake and/or unstake, rebase is performed.
And then function distributor in Distributor.sol is called.
But in that function, I have noticed there is an array variable called "info".
I understood this variable stores stakers' addresses. But I can't find when the user's address is added to this variable.
I have tried to find functions "addRecipient", "removeRecipient" and "setAdjustment" in contract and frontend, but have nothing.
Is there any other platform to call policy functions?
When is the user added to the info array variable?
Looking forward to your kind answers.
Thanks.

**Comment by Cazs03** [comment]
Same question need bit more explanations missing in docs

**Comment by thlee93** [comment]
In my understanding, info variable in the Distributor contract only stores the address of the staking contract (check https://etherscan.io/address/0xeeeb97A127a342656191E0313DF33D58D06B2E05#readContract).

Staker's balance of sOHM is rather being updated by `_gonsPerFragment` variable in the sOHM contract. With total supply of the token being increased, balance of each staker's token is increased during the operation of `_gonBalances[who].div(_gonsPerFragment)`. 

I leave my comment here to help others who try to understand the code.
