### ISSUE TITLE
BondDepository.sol for v1.1 does not accept Deposits as per script

### ISSUE THREAD

**Issue by cleancoindev** [OlympusDAO/olympus-contracts#110]
![Screenshot - 11_24_2021 , 8_19_11 AM](https://user-images.githubusercontent.com/31389482/143293573-ffaf77c5-1658-4441-81c4-ba2ccfc022ee.png)

I get a reversion -32015 - which is apparently an "Address not payable" error when i try to deploy and then do the final test of the deposits into the Bonds.

I have tried numerous times now and keep getting the same end result for a week now on 2 different chains.  

Any idea what the issue may be?

Thanks!

**Comment by NoblePaladin** [comment]
Hey @cleancoindev,

Could you try working with the V2 branch? V1.1 is not actively maintained.
It would be great if Olympus Team updates the default branch for this project too.

**Comment by cleancoindev** [comment]
I will do so and report back the results, thanks for the heads up!  I didn't notice the v2!

**Comment by ind-igo** [comment]
Main branch has been updated to V2. Please use this instead.
