### ISSUE TITLE
UUPS Workflow Model (ERC 1967)

### ISSUE THREAD

**Issue by NoblePaladin** [OlympusDAO/olympus-contracts#111]
Hello friends,

I've been working on a fork of the code. However, I've been reviewing the code and am curious if you guys are open or interested to the UUPS Contract Model.

The scope of work involved for UUPS is fairly large, so I understand if I may end up being a hard fork. But, it would certainly prove useful for maintaining deployments on the original source. I've left references below for discussion.

- https://eips.ethereum.org/EIPS/eip-1967

- https://docs.openzeppelin.com/contracts/4.x/api/proxy

**Comment by ind-igo** [comment]
No, the system was intended to be immutable. We may use Proxies in the future for certain contracts, but at the moment we are not.
