### ISSUE TITLE
[BondDepository] Capacity modified but not used

### ISSUE THREAD

**Issue by ICONationDevTeam** [OlympusDAO/olympus-contracts#123]
https://github.com/OlympusDAO/olympus-contracts/blob/9a2dbdba0d458aac47ef7cbbfdf7716d4df19a17/contracts/BondDepository.sol#L218

https://github.com/OlympusDAO/olympus-contracts/blob/9a2dbdba0d458aac47ef7cbbfdf7716d4df19a17/contracts/BondDepository.sol#L222

The `capacity` field of the `info` memory structure is modified but never used.

**Comment by ind-igo** [comment]
We're currently working on the V2 bonds. This bond code is not the most up-to-date. This has been fixed in the new iteration.

**Comment by ICONationDevTeam** [comment]
Hello @ind-igo ! Thank you. Where may I find the latest up to date V2 code please?
Cheers
