### ISSUE TITLE
What does 'gon' stand for?

### ISSUE THREAD

**Issue by pvys** [OlympusDAO/olympus-contracts#129]
Currently read through the contracts, but get stuck at sOlympusERC20.sol.
What does 'gon' stand for? Is it an abbreviation of something?

**Comment by Joe-mcgee** [comment]
https://github.com/ampleforth/ampleforth-contracts/blob/68049dc4ba653458b35af5d2f34113f3d55ae6d5/contracts/UFragments.sol

Digging around the discord to this same question, looks like it came from this

**Comment by Mansarde** [comment]
joe-mcgee already gave you an answer as to what gons are used for in the contract.
But as to the meaning of the word itself I have found this from the official discord:
![image](https://user-images.githubusercontent.com/847687/146122330-54f9cc56-dc81-4e43-bca0-2a0572a122b1.png)

I'm always curious regarding the etymology of words in projects, so it's extra frustrating when it's not mentioned ANYWHERE in the documentation or in the code. In this particular instance it was fortunate that it's been mentioned at least once in the Discord.
For me, having to use a word without knowing its meaning is like using a math formula without understanding why it works. 😆

**Comment by Joe-mcgee** [comment]
same, i'm sure more than a few of us dug around asking about this though.  Why Gons, Why Fragments, it seems to me its 'because thats what ampleforth did and we just spliced it in` but, why did ampleforth do it, 

why framents,
why gons,
aaaaah
