### ISSUE TITLE
Suggestion to move to Foundry as part of the test suite revamp

### ISSUE THREAD

**Issue by kombu-takana** [OlympusDAO/olympus-contracts#130]
# References
- https://github.com/gakonst/foundry
- Blog Post: https://www.paradigm.xyz/2021/12/introducing-the-foundry-ethereum-development-toolbox/

# tl;dr
Using Foundry's toolkit, developers will be able to write unit tests in Solidity rather than in JS/TS.

**Comment by ind-igo** [comment]
We already have dapptools. Would like to move to foundry once tracing is implemented fully (soon!).
