### ISSUE TITLE
Testing gOHM on rinkeby

### ISSUE THREAD

**Issue by werfish** [OlympusDAO/olympus-contracts#142]
HI 

I writing automated solution for Olympus Staking/Unstaking and trading. How do I get test OHM on Rinkeby network?
Do you have a link to a faucet?

Thanks and best regards.

**Comment by ind-igo** [comment]
There is a faucet on rinkeby somewhere... @lolchocotaco or @JExtor may be able to help.

**Comment by lolchocotaco** [comment]
Our testnet deployments are here: 
https://github.com/OlympusDAO/olympus-contracts/tree/main/deployments/rinkeby

as long as an ohm faucet :)
