### ISSUE TITLE
Transfer from BondDepository, not User

### ISSUE THREAD

**Issue by rlkelly** [OlympusDAO/olympus-contracts#156]
https://github.com/OlympusDAO/olympus-contracts/blob/5a0712b04df861350eafaed00d34375de0354871/contracts/BondDepository.sol#L228

This feels incorrect to me.  Nothing in the BondDepository actually transfers the principal.  I believe this should be from the user.

**Comment by lolchocotaco** [comment]
This is an old bondDepository thats no longer used! Going to close this.
