### ISSUE TITLE
[Core - Allocators] Allocator system redesign

### ISSUE THREAD

**Issue by ind-igo** [OlympusDAO/olympus-contracts#173]

**Comment by mirru2532** [comment]
Complete:
Interfaces + TreasuryExtender.sol and BaseAllocator.sol
WIP:
TreasuryExtender tests
TODO:
BaseAllocator (with mock) tests
Implement FUSE pool with interface

**Comment by mirru2532** [comment]
Complete:
Interfaces + TreasuryExtender.sol and BaseAllocator.sol
TreasuryExtender tests
WIP:
BaseAllocator (with mock) tests
TODO:
Implement FUSE pool with interface

**Comment by mirru2532** [comment]
All tests and NATSPEC are done, this should be moved to under audit.

**Comment by mirru2532** [comment]
Moved it to under audit.
