### ISSUE TITLE
Staking in GH != Staking on mainnet

### ISSUE THREAD

**Issue by CarsonCase** [OlympusDAO/olympus-contracts#184]
Staking here: https://etherscan.io/address/0xfd31c7d00ca47653c6ce64af53c1571f9c36566a#code

is not the same as the staking here. This is specifically an issue because the function signature's for stake/unstake are different that what's actually deployed so my code is breaking when trying to connect with the real ohm. I can't find where the code here on GH is actually deployed. If anyone has an up to date IStaking interface I could certainly use one

**Comment by FaysalM** [comment]
Are you sure you trying to look at v1? That's the v1 contract address.

**Comment by CarsonCase** [comment]
> 

I was using this "new staking" for V2. I see now there's the V2 staking contract in the readme. Thank you
https://docs.olympusdao.finance/main/contracts/staking
