### ISSUE TITLE
deployment addresses

### ISSUE THREAD

**Issue by mmgl76** [OlympusDAO/olympus-contracts#326]
Deployment addresses are documented for mainnet only while there are few other chains supported for bonds etc. Where can these addresses be found? Apologies for asking here but I exhausted all other channels I could think of.

**Comment by brightiron** [comment]
Please see https://github.com/OlympusDAO/olympus-contracts/pull/317 for incoming goerli addresses and the Readme for rinkeby addresses.

**Comment by mmgl76** [comment]
Thanks
