### ISSUE TITLE
import common contract code

### ISSUE THREAD

**Issue by benjyz** [OlympusDAO/olympus-contracts#74]
the contracts would be nicer to read if they had the common contract code as imports

**Comment by sam-goodwin** [comment]
Yeah I am wondering the same. Are they copied verbatim or are there modifications of the Open Zeppelin implementations?

**Comment by benjyz** [comment]
there are some changes. in V2 its in the libraries folder

https://github.com/OlympusDAO/olympus-contracts/tree/Version-2

**Comment by benjyz** [comment]
there is a TODO here

https://github.com/OlympusDAO/olympus-contracts/blob/Version-2/contracts/libraries/SafeMath.sol#L5

**Comment by ind-igo** [comment]
This is something that was done to have all relevant files in the repo (to go along with the immutability of the protocol), but has shown itself to be a complete pain in the ass. We intend to use standardized common contracts in the future, but for now we will keep it as it is for now.
