### ISSUE TITLE
newer solidity version does not need safemath

### ISSUE THREAD

**Issue by benjyz** [OlympusDAO/olympus-contracts#75]
a suggestion. contracts are more readable without safemath
https://ethereum.stackexchange.com/questions/91367/is-the-safemath-library-obsolete-in-solidity-0-8-0

**Comment by parseb** [comment]
Another suggestion, Solidity 0.8.4 introduces custom errors. Their use can lead to a reduction in gas. The error takes arguments and its name can be descriptive. 

Should be closed. Not an issue.

**Comment by ind-igo** [comment]
We're aware of 0.8.0. We will be upgrading our next iteration to this.
