### ISSUE TITLE
When will give out local deployments guide?

### ISSUE THREAD

**Issue by banjuanshua** [OlympusDAO/olympus-contracts#90]
I'm new in solidity, hope for a guide how these code run in local ganache chain. Tanks very much.

**Comment by ddfbrgfb3** [comment]
@banjuanshua you can become a contributor instead of waiting for "wen local guide" answer ser

https://docs.olympusdao.finance/main/get-involved/contribute

**Comment by ferbsferbs** [comment]
> I'm new in solidity, hope for a guide how these code run in local ganache chain. Tanks very much.

Any updates?

**Comment by NoblePaladin** [comment]
Hey friends.
I will send an update for a local deployment (with Ganache) soon.

Will send a PR soon.

**Comment by ferbsferbs** [comment]
> Hey friends. I will send an update for a local deployment (with Ganache) soon.
> 
> Will send a PR soon.

You are the best!
Thanks

**Comment by ind-igo** [comment]
The current V2 uses Hardhat-deploy and has an almost full deployment system.
